### ISSUE TITLE
解密失败

### ISSUE THREAD

**Issue by PackageInstaller** [ihopenot/LpkUnpacker#8]
尝试用这位老哥说的[方法](https://github.com/ihopenot/LpkUnpacker/issues/4#issuecomment-1475556979)加载，执行`python LpkUnpacker.py`后，报错如下

```
Traceback (most recent call last):
  File "/home/Neko/LpkUnpacker/LpkUnpacker.py", line 6, in <module>
    loader.extract("./new")
  File "/home/Neko/LpkUnpacker/Core/lpk_loader.py", line 42, in extract
    self.extract_costume(chara["costume"][i], subdir)
  File "/home/Neko/LpkUnpacker/Core/lpk_loader.py", line 57, in extract_costume
    self.check_decrypt(filename)
  File "/home/Neko/LpkUnpacker/Core/lpk_loader.py", line 116, in check_decrypt
    self.decrypt_file(filename).decode(encoding="utf8")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Neko/LpkUnpacker/Core/lpk_loader.py", line 161, in decrypt_file
    return self.decrypt_data(filename, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Neko/LpkUnpacker/Core/lpk_loader.py", line 164, in decrypt_data
    key = self.getkey(filename)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/Neko/LpkUnpacker/Core/lpk_loader.py", line 153, in getkey
    return genkey(self.mlve_config["id"] + self.config["fileId"] + file + self.config["metaData"])
                                           ~~~~~~~~~~~^^^^^^^^^^
KeyError: 'fileId'
```

这是lpk和config,大佬帮我康康吧
[lpk.tar.gz](https://github.com/ihopenot/LpkUnpacker/files/12610797/lpk.tar.gz)

**Comment by ihopenot** [comment]
## 目录结构

```
.
├── Core
│   ├── lpk_loader.py
│   └── utils.py
├── LpkUnpacker.py
├── README.md
├── output              <==
├── requirements.txt
└── lpkfolder           <==
    ├── target.lpk      <==
    └── config.json     <==
```

## 使用方法

1. clone这个仓库
2. 在仓库目录下新建output和lpkfolder两个文件夹
3. 把你的lpk和config.json丢到lpkfolder里去
4. 在仓库目录下运行```python LpkUnpacker.py -c lpkfolder/config.json lpkfolder/target.lpk output```

使用pycharm请自行搜索怎么添加python启动参数
